nxtend-team/nxtend

libs/ionic-react/README.md
libs/ionic-react/collection.json
libs/ionic-react/src/schematics/init/init.spec.ts
libs/ionic-react/src/schematics/init/init.ts
libs/ionic-react/src/schematics/init/schema.d.ts
libs/ionic-react/src/schematics/init/schema.json
libs/ionic-react/src/utils/testing.ts
libs/ionic-react/src/utils/versions.ts
package.json
yarn.lock

feat(ionic-react): init schematic

---

libs/ionic-react/src/schematics/application/files/src/app/app.tsx.template
libs/ionic-react/src/schematics/application/files/src/app/theme/variables.__style__.template
libs/ionic-react/src/utils/versions.ts

chore(ionic-react): upgrade Ionic to v5

---

LICENSE

chore(core): add MIT license

---

libs/ionic-react/src/schematics/application/files/src/app/app.spec.tsx.template
libs/ionic-react/src/schematics/application/schema.d.ts
libs/ionic-react/src/schematics/application/schema.json
libs/ionic-react/src/schematics/application/schematic.ts

fix(ionic-react): remove routing parameter

---

libs/ionic-react/plugins/webpack.ts
libs/ionic-react/src/schematics/application/schematic.ts

fix(ionic-react): polyfill Node

---

apps/ionic-react-e2e/tests/application.test.ts
libs/ionic-react/src/schematics/application/schematic.spec.ts
libs/ionic-react/src/schematics/application/schematic.ts

feat(ionic-react): support JS in application schematic

---

PULL_REQUEST_TEMPLATE.md

chore(core): add pull request template

---

CONTRIBUTING.md

This PR adds a contributing file to inform others on how to best contribute to the project.
Resolves #46

chore(core): add contributing file

---

libs/ionic-react/README.md

Update the README for the `ionic-react` library.
Resolves #44

chore(ionic-react): update README

---

README.md

Update the parent `README.md`.
Resolves #3

docs(core): update README

---

libs/ionic-react/package.json

Release @nxtend/ionic-react 0.2.0-beta.1

---

libs/ionic-react/src/schematics/application/files/blank/src/app/__appFileName__.spec.tsx.template

fix(ionic-react): fix generated unit tests

---

libs/ionic-react/migrations.json
libs/ionic-react/src/migrations/update-1-0-1/update-1-0-1.spec.ts
libs/ionic-react/src/migrations/update-1-0-1/update-1-0-1.ts
libs/ionic-react/src/utils/versions.ts

chore(ionic-react): upgrade Ionic to 5.0.5

---

libs/ionic-react/package.json

Release @nxtend/ionic-react 1.0.1

---

.github/workflows/nodejs.yml

chore(ionic-react): add GitHub Actions config

---

libs/ionic-react/CHANGELOG.md
libs/ionic-react/migrations.json
libs/ionic-react/src/migrations/update-1-0-2/update-1-0-2.spec.ts
libs/ionic-react/src/migrations/update-1-0-2/update-1-0-2.ts
libs/ionic-react/src/utils/versions.ts

Upgrade Ionic to 5.0.7.
Resolves #85

chore(ionic-react): upgrade Ionic to 5.0.7

---

libs/ionic-react/CHANGELOG.md
libs/ionic-react/migrations.json
libs/ionic-react/src/migrations/update-1-1-0/update-1-1-0.spec.ts
libs/ionic-react/src/migrations/update-1-1-0/update-1-1-0.ts
libs/ionic-react/src/utils/versions.ts

chore(ionic-react): upgrade @testing-library/jest-dom to 5.5.0

---

libs/ionic-react/CHANGELOG.md
libs/ionic-react/migrations.json
libs/ionic-react/src/migrations/update-2-0-0/update-2-0-0.spec.ts
libs/ionic-react/src/migrations/update-2-0-0/update-2-0-0.ts
libs/ionic-react/src/utils/versions.ts

chore(ionic-react): update @testing-library/user-event to 10.0.1

---

.vscode/extensions.json

Recommended extensions

---

libs/ionic-react/CHANGELOG.md
libs/ionic-react/migrations.json
libs/ionic-react/src/migrations/update-2-0-0/default-collection-2-0-0.spec.ts
libs/ionic-react/src/migrations/update-2-0-0/default-collection-2-0-0.ts
libs/ionic-react/src/schematics/application/lib/update-workspace.ts
libs/ionic-react/src/schematics/application/schematic.spec.ts
libs/ionic-react/src/schematics/application/schematic.ts
libs/ionic-react/src/schematics/init/schematic.spec.ts
libs/ionic-react/src/schematics/init/schematic.ts

feat(ionic-react): set @nxtend/ionic-react as the default schematic

---

libs/ionic-react/CHANGELOG.md
libs/ionic-react/src/schematics/application/schematic.ts

fix(ionic-react): honor `skipFormat` flag

---

libs/ionic-react/CHANGELOG.md
libs/ionic-react/MIGRATION.md
libs/ionic-react/migrations.json
libs/ionic-react/src/migrations/update-2-0-0/update-2-0-0.ts
libs/ionic-react/src/migrations/update-2-0-0/updated-templates-2-0-0.ts
libs/ionic-react/src/schematics/application/files/blank/src/app/pages/__homeFileName__.__style__.template
libs/ionic-react/src/schematics/application/files/blank/src/app/theme/variables.__style__.template
libs/ionic-react/src/schematics/application/files/blank/src/index.html.template

chore(ionic-react): add color-scheme meta tag in application schematic
https://github.com/ionic-team/starters/pull/1201
fix(starters): update theming vars in application schematic
https://github.com/ionic-team/starters/pull/1202
Resolves #98

chore(ionic-react): update Ionic starter in application schematic

---

libs/ionic-react/package.json

Release @nxtend/ionic-react 2.0.0

---

libs/ionic-react/MIGRATION.md

fix(ionic-react): add missing PR link to MIGRATION.md

---

libs/ionic-react/CHANGELOG.md
libs/ionic-react/src/schematics/application/schema.json
libs/ionic-react/src/schematics/application/schematic.spec.ts

feat(ionic-react): default application linter to ESLint

---

libs/ionic-react/CHANGELOG.md
libs/ionic-react/src/schematics/application/files/blank/src/app/__appFileName__.tsx.template
libs/ionic-react/src/schematics/application/files/blank/src/app/components/__exploreContainerFileName__.tsx.template
libs/ionic-react/src/schematics/application/files/blank/src/app/pages/__homeFileName__.tsx.template

fix(ionic-react): fix styled-components styles

---

libs/ionic-react/package.json

Release @nxtend/ionic-react 2.1.0

---

libs/ionic-react/CHANGELOG.md
libs/ionic-react/migrations.json
libs/ionic-react/src/migrations/upgrade-ionic-2-2-0/upgrade-ionic-2-2-0.spec.ts
libs/ionic-react/src/migrations/upgrade-ionic-2-2-0/upgrade-ionic-2-2-0.ts
libs/ionic-react/src/utils/versions.ts

chore(ionic-react): upgrade Ionic to 5.1.0

---

libs/ionic-react/src/schematics/application/files/blank/src/app/__appFileName__.tsx.template
libs/ionic-react/src/schematics/application/files/blank/src/app/components/__exploreContainerFileName__.tsx.template

cleanup(ionic-react): clean up whitespace in component templates

---

apps/ionic-react-e2e/tests/application.test.ts

chore(ionic-react): e2e test generated apps in e2e tests

---

libs/ionic-react/src/schematics/application/schematic.spec.ts

chore(ionic-react): refactor unit tests

---

apps/ionic-react-e2e/tests/application.test.ts
libs/ionic-react/CHANGELOG.md
libs/ionic-react/src/schematics/application/files/blank/src/app/__appFileName__.tsx.template

fix(ionic-react): fix generating global styles for Emotion

---

babel.config.json
libs/ionic-react/.babelrc
package.json
workspace.json
yarn.lock

chore(core): upgrade Nx to 9.4.3

---

package.json
yarn.lock

chore(core): upgrade Nx to 9.4.5

---

apps/ionic-react-e2e/tests/application.test.ts
libs/ionic-react/CHANGELOG.md
libs/ionic-react/migrations.json
libs/ionic-react/src/migrations/update-2-2-0/upgrade-ionic-2-2-0.spec.ts
libs/ionic-react/src/utils/versions.ts

chore(ionic-react): upgrade Ionic to 5.2.2

---

apps/docs/blog/2020-06-26-ionic-react-2.2.0.md
libs/ionic-react/package.json

Ionic react/relese 2.2.0 blog

---

libs/ionic-react/CHANGELOG.md
libs/ionic-react/migrations.json
libs/ionic-react/package.json
libs/ionic-react/src/migrations/update-3-0-0/upgrade-testing-library-3-0-0.spec.ts
libs/ionic-react/src/migrations/update-3-0-0/upgrade-testing-library-3-0-0.ts
libs/ionic-react/src/utils/versions.ts

chore(ionic-react): upgrade Testing Library dependencies

---

apps/docs/docs/nxtend/upgrades.md
apps/docs/sidebars.js

docs(docs): add upgrade documentation

---

apps/docs/docs/ionic-react/getting-started.md
libs/ionic-react/collection.json
libs/ionic-react/src/schematics/application/schema.json

chore(ionic-react): unify schema punctuation

---

libs/ionic-react/CHANGELOG.md
libs/ionic-react/migrations.json
libs/ionic-react/src/migrations/update-3-0-1/upgrade-ionic-3-0-1.spec.ts
libs/ionic-react/src/migrations/update-3-0-1/upgrade-ionic-3-0-1.ts
libs/ionic-react/src/utils/versions.ts

chore(ionic-react): upgrade Ionic to 5.2.3

---

libs/ionic-react/package.json

Release @nxtend/ionic-react 3.0.1

---

apps/docs/docs/capacitor/getting-started.md

Updated documentation 
Resolves #

 docs(capacitor): add --platform to commands in "Getting Started"

---

libs/ionic-react/src/schematics/application/lib/add-dependencies.ts
libs/ionic-react/src/schematics/application/lib/external-schematic.ts
libs/ionic-react/src/schematics/application/lib/files.ts
libs/ionic-react/src/schematics/application/lib/normalize-options.ts
libs/ionic-react/src/schematics/application/lib/update-workspace.ts
libs/ionic-react/src/schematics/application/schematic.ts
libs/ionic-react/src/schematics/init/lib/add-dependencies.ts
libs/ionic-react/src/schematics/init/schematic.ts

Better organize the `@nxtend/ionic-react` schematics based on some inspiration from the Nx repo.
Resolves #178

chore(ionic-react): better organize schematics

---

packages/ionic-react/CHANGELOG.md
packages/ionic-react/src/schematics/init/lib/add-dependencies.ts
packages/ionic-react/src/schematics/init/schematic.spec.ts
packages/ionic-react/src/utils/versions.ts

fix(ionic-react): don't add @nxtend/ionic-react with init schematic

---

packages/ionic-react/CHANGELOG.md
packages/ionic-react/src/schematics/init/lib/add-capacitor-plugin.ts
packages/ionic-react/src/schematics/init/schematic.spec.ts
packages/ionic-react/src/schematics/init/schematic.ts
packages/ionic-react/src/utils/versions.ts

fix(ionic-react): add @nxtend/capacitor 1.0.0 instead of *

---

.github/workflows/nx-affected.yml
nx.json
package.json
yarn.lock

feat(core): add Nx Cloud plugin

---

packages/docs/blog/2020-07-16-ionic-react-3.0.3.md
packages/ionic-react/package.json

Release @nxtend/ionic-react 3.0.3

---

packages/ionic-react/CHANGELOG.md
packages/ionic-react/src/schematics/application/lib/cypress.ts

This change improves the way we update the users `tsconfig.json` for Cypress. This is a generally better way of handling this change, but also is necessary for Nx 10.
Resolves #198

fix(ionic-react): improve updating `tsconfig.json` in app schematic

---

packages/ionic-react/package.json

Release @nxtend/ionic-react 3.0.5

---

.github/workflows/nx-affected.yml

chore(core): cache node_modules/ in GitHub Action

---

package.json

The Prettier pre-commit hook was not accounted for when the workspace layout was modified.
Resolves #201

chore(core): update Prettier hook to format updated workspace layout

---

README.md
packages/capacitor/jest.config.js
packages/capacitor/package.json
packages/ionic-react/jest.config.js
packages/ionic-react/package.json

chore(core): update references of libs/ directory to packages/ directory

---

packages/capacitor/package.json
packages/ionic-react/package.json

chore(core): update package.json homepages

---

packages/capacitor/src/schematics/init/lib/add-dependencies.ts
packages/capacitor/src/schematics/init/schematic.spec.ts
packages/capacitor/src/utils/versions.ts

chore(capacitor): don't add @nxtend/capacitor with init schematic

---

packages/ionic-react/CHANGELOG.md
packages/ionic-react/migrations.json
packages/ionic-react/src/migrations/update-3-1-0/upgrade-ionic-3-1-0.spec.ts
packages/ionic-react/src/migrations/update-3-1-0/upgrade-ionic-3-1-0.ts
packages/ionic-react/src/utils/versions.ts

chore(ionic-react): upgrade Ionic to 5.3.1

---

packages/ionic-react/src/schematics/application/schematic.spec.ts

fix(ionic-react): fix application schematic unit test for Capacitor

---

nx.json

fix(ionic-react): add @nxtend/capacitor as implicit dependency

---

packages/capacitor/CHANGELOG.md
packages/capacitor/migrations.json
packages/capacitor/src/migrations/update-1-1-0/upgrade-capacitor-1-1-0.spec.ts
packages/capacitor/src/migrations/update-1-1-0/upgrade-capacitor-1-1-0.ts
packages/capacitor/src/schematics/init/lib/add-dependencies.ts
packages/capacitor/src/utils/versions.ts

Upgrade Capacitor dependencies to 2.4.0.
Resolves #207

chore(capacitor): upgrade Capacitor to 2.4.0

---

e2e/ionic-react-e2e/tests/application.test.ts
packages/ionic-react/package.json

This should have been done when adding @nxtend/capacitor as an implicit dependency.
Resolves #

fix(ionic-react): add @nxtend/capacitor as a peer dependency

---

packages/capacitor/package.json
packages/docs/blog/2020-08-15-capacitor-1.1.0.md

Release @nxtend/capacitor 1.1.0

---

package.json
yarn.lock

chore(core): upgrade Nx Cloud to 10.0.0

---

e2e/capacitor-e2e/tests/capacitor-project.test.ts
packages/ionic-react/CHANGELOG.md
packages/ionic-react/migrations.json
packages/ionic-react/src/migrations/update-3-2-0/upgrade-nxtend-capacitor-3-2-0.spec.ts
packages/ionic-react/src/migrations/update-3-2-0/upgrade-nxtend-capacitor-3-2-0.ts
packages/ionic-react/src/utils/versions.ts

chore(ionic-react): upgrade @nxtend/Capacitor app dependency to 1.1.0

---

.github/workflows/nx-affected.yml

chore(core): support forked PR's with GitHub action

---

packages/ionic-react/CHANGELOG.md
packages/ionic-react/migrations.json
packages/ionic-react/src/migrations/update-3-2-0/update-3-2-0.spec.ts
packages/ionic-react/src/migrations/update-3-2-0/update-3-2-0.ts
packages/ionic-react/src/utils/versions.ts

chore(ionic-react): update testing libs app deps

---

packages/docs/blog/2020-09-13-ionic-react-3.1.0.md
packages/ionic-react/CHANGELOG.md
packages/ionic-react/package.json

Release @nxtend/ionic-react 3.1.0

---

packages/docs/blog/2020-09-13-ionic-react-3.1.0.md
packages/ionic-react/CHANGELOG.md
packages/ionic-react/migrations.json
packages/ionic-react/src/migrations/update-3-2-0/update-3-2-0.spec.ts
packages/ionic-react/src/utils/versions.ts

chore(ionic-react): update @testing-library/user-event app dep to 12.1.5

---

e2e/ionic-angular-e2e/jest.config.js
e2e/ionic-angular-e2e/tests/ionic-angular.test.ts
e2e/ionic-angular-e2e/tsconfig.json
e2e/ionic-angular-e2e/tsconfig.spec.json
nx.json
packages/ionic-angular/.eslintrc
packages/ionic-angular/README.md
packages/ionic-angular/builders.json
packages/ionic-angular/collection.json
packages/ionic-angular/jest.config.js
packages/ionic-angular/package.json
packages/ionic-angular/src/builders/build/builder.spec.ts
packages/ionic-angular/src/builders/build/builder.ts
packages/ionic-angular/src/builders/build/schema.d.ts
packages/ionic-angular/src/builders/build/schema.json
packages/ionic-angular/src/schematics/ionic-angular/files/src/index.ts.template
packages/ionic-angular/src/schematics/ionic-angular/schema.d.ts
packages/ionic-angular/src/schematics/ionic-angular/schema.json
packages/ionic-angular/src/schematics/ionic-angular/schematic.spec.ts
packages/ionic-angular/src/schematics/ionic-angular/schematic.ts
packages/ionic-angular/tsconfig.json
packages/ionic-angular/tsconfig.lib.json
packages/ionic-angular/tsconfig.spec.json
tsconfig.base.json
workspace.json

The main purpose of this PR is to get the scaffolding of the `ionic-angular` plugin into the main branch.
Resolves #

feat(ionic-angular): generate ionic-angular plugin

---

.github/workflows/nx-affected.yml
nx.json
packages/docs/docusaurus.config.js

chore(core): change default base branch to main

---

e2e/capacitor-e2e/tests/capacitor-project.test.ts
packages/capacitor/CHANGELOG.md
packages/capacitor/MIGRATION.md
packages/capacitor/migrations.json
packages/capacitor/src/migrations/update-2-0-0/update-2-0-0.ts
packages/capacitor/src/schematics/capacitor-project/lib/add-project.ts
packages/capacitor/src/schematics/capacitor-project/lib/generate-files.ts
packages/capacitor/src/schematics/capacitor-project/lib/normalize-options.ts
packages/capacitor/src/schematics/capacitor-project/schema.d.ts
packages/capacitor/src/schematics/capacitor-project/schema.json
packages/capacitor/src/schematics/capacitor-project/schematic.spec.ts
packages/capacitor/src/schematics/capacitor-project/schematic.ts
packages/docs/blog/2020-10-08-capacitor-2.0.0.md
packages/docs/docs/capacitor/getting-started.md
packages/docs/docs/capacitor/schematics/capacitor-project.md
packages/docs/docs/ionic-react/getting-started.md
packages/ionic-react/src/schematics/application/schematic.spec.ts
workspace.json

feat(capacitor): add Capacitor configs to frontend application

---

packages/docs/docs/capacitor/getting-started.md

docs(capacitor): build project before using native platforms

---

README.md
packages/docs/docs/nxtend/introduction.md
packages/docs/docs/nxtend/upgrades.md
packages/docs/docusaurus.config.js
packages/docs/sidebars.js

docs(core): rebrand to Nxtend

---

packages/capacitor/MIGRATION.md
packages/capacitor/src/schematics/init/lib/add-dependencies.ts
packages/capacitor/src/schematics/init/schematic.spec.ts

chore(capacitor): don't install @capacitor/cli to the root package.json

---

packages/capacitor/CHANGELOG.md
packages/capacitor/migrations.json
packages/capacitor/src/migrations/update-2-0-0/update-2-0-0.spec.ts
packages/capacitor/src/migrations/update-2-0-0/update-2-0-0.ts
packages/capacitor/src/utils/versions.ts

chore(capacitor): update Capacitor to 2.4.2

---

packages/docs/docs/capacitor/getting-started.md
packages/docs/docs/ionic-react/getting-started.md

docs(ionic-react): small updates to Getting Started

---

packages/capacitor/src/schematics/init/schematic.spec.ts

chore(capacitor): update init unit tests

---

packages/ionic-react/src/schematics/application/files/jest/src/test-setup.ts.template
packages/ionic-react/src/schematics/init/lib/add-dependencies.ts
packages/ionic-react/src/schematics/init/schematic.spec.ts
packages/ionic-react/src/utils/versions.ts

fix(ionic-react): don't install Testing Library dependencies

---

packages/ionic-react/CHANGELOG.md
packages/ionic-react/migrations.json
packages/ionic-react/src/migrations/update-4-0-0/update-4-0-0.spec.ts
packages/ionic-react/src/migrations/update-4-0-0/update-4-0-0.ts
packages/ionic-react/src/utils/versions.ts

feat(ionic-react): update Ionic to 5.4.1

---

e2e/ionic-react-e2e/tests/ionic-react.test.ts
packages/ionic-react/CHANGELOG.md
packages/ionic-react/migrations.json
packages/ionic-react/src/migrations/update-4-0-0/add-ionic-config-4-0-0.spec.ts
packages/ionic-react/src/migrations/update-4-0-0/add-ionic-config-4-0-0.ts
packages/ionic-react/src/schematics/application/files/ionic/base/ionic.config.json.template

Add an `ionic.config.json` to all Ionic React apps.
Resolves #255

feat(ionic-react): add ionic.config.json

---

packages/docs/blog/2020-10-25-ionic-react-4.0.0.md
packages/ionic-react/CHANGELOG.md
packages/ionic-react/src/schematics/application/files/ionic/base/src/app/theme/variables.__style__.template
packages/ionic-react/src/schematics/application/files/ionic/blank/src/app/pages/__homeFileName__.tsx.template

chore(ionic-react): update stater template

---

e2e/ionic-react-e2e/tests/ionic-react.test.ts
packages/docs/blog/2020-10-25-ionic-react-4.0.0.md
packages/docs/docs/ionic-react/getting-started.md
packages/docs/docs/ionic-react/schematics/application.md
packages/ionic-react/CHANGELOG.md
packages/ionic-react/src/schematics/application/files/ionic/blank/src/app/__appFileName__.tsx.template
packages/ionic-react/src/schematics/application/schema.d.ts
packages/ionic-react/src/schematics/application/schema.json
packages/ionic-react/src/schematics/application/schematic.spec.ts

chore(ionic-react): remove disableSanitizer flag from app schematic

---

packages/capacitor/CHANGELOG.md
packages/capacitor/package.json
packages/docs/blog/2020-11-03-capacitor-2.0.2.md

Release @nxtend/capacitor 2.0.1

---

packages/docs/blog/2020-11-04-ionic-react-4.0.0.md
packages/ionic-react/package.json

Release @nxtend/ionic-react 4.0.0

---

e2e/ionic-angular-e2e/tests/ionic-angular.test.ts
packages/ionic-angular/src/schematics/application/files/src/app/home/home.page.html.template
packages/ionic-angular/src/schematics/application/lib/add-project.ts
packages/ionic-angular/src/schematics/application/lib/files.ts
packages/ionic-angular/src/schematics/application/lib/normalize-options.ts
packages/ionic-angular/src/schematics/application/schema.d.ts
packages/ionic-angular/src/schematics/application/schema.json
packages/ionic-angular/src/schematics/application/schematic.spec.ts

feat(ionic-angular): add directory parameter to application schematic

---

e2e/ionic-angular-e2e/tests/ionic-angular.test.ts
packages/ionic-angular/src/schematics/application/files/src/app/home/home.page.html.template
packages/ionic-angular/src/schematics/application/lib/add-project.ts
packages/ionic-angular/src/schematics/application/lib/normalize-options.ts
packages/ionic-angular/src/schematics/application/lib/update-nx-json.ts
packages/ionic-angular/src/schematics/application/schema.d.ts
packages/ionic-angular/src/schematics/application/schema.json
packages/ionic-angular/src/schematics/application/schematic.spec.ts
packages/ionic-angular/src/schematics/application/schematic.ts

feat(ionic-angular): add tags parameter to application schematic

---

e2e/ionic-angular-e2e/tests/ionic-angular.test.ts
packages/ionic-angular/src/schematics/application/lib/external-schematic.ts
packages/ionic-angular/src/schematics/application/lib/normalize-options.ts
packages/ionic-angular/src/schematics/application/schema.d.ts
packages/ionic-angular/src/schematics/application/schema.json
packages/ionic-angular/src/schematics/application/schematic.spec.ts
packages/ionic-angular/src/schematics/application/schematic.ts
packages/ionic-angular/src/utils/versions.ts

feat(ionic-angular): add Capacitor support to application schematic

---

packages/ionic-react/CHANGELOG.md
packages/ionic-react/src/utils/versions.ts

chore(ionic-react): initialize plugin with @nxtend/capacitor 2.0.2

---

packages/ionic-react/package.json

Release @nxtend/ionic-react 4.1.0

---

packages/docs/docs/ionic-angular/getting-started.md
packages/docs/docs/ionic-angular/overview.md
packages/docs/docs/ionic-angular/schematics/application.md
packages/docs/docs/ionic-angular/schematics/init.md
packages/docs/sidebars.js

docs(ionic-angular): add initial docs

---

packages/docs/docs/ionic-react/overview.md

docs(ionic-react): remove reference of extending @nrwl/react

---

packages/docs/blog/2020-11-13-ionic-angular-1.0.0.md
packages/ionic-angular/package.json

Release @nxtend/ionic-angular 1.0.0

---

packages/docs/docs/ionic-angular/getting-started.md
packages/docs/docs/ionic-react/getting-started.md

docs(ionic-angular/ionic-react): improve Capacitor usage

---

.github/workflows/nx-affected.yml

chore(core): check formatting in GitHub action

---

e2e/ionic-react-e2e/tests/ionic-react.test.ts
packages/docs/blog/draft/2020-12-02-ionic-react-5.0.0.md
packages/docs/docs/ionic-react/getting-started.md
packages/docs/docs/ionic-react/schematics/application.md
packages/ionic-react/CHANGELOG.md
packages/ionic-react/src/schematics/application/files/ionic/blank/src/app/__appFileName__.tsx.template
packages/ionic-react/src/schematics/application/files/ionic/blank/src/app/components/__exploreContainerFileName__.tsx.template
packages/ionic-react/src/schematics/application/files/ionic/blank/src/app/pages/__homeFileName__.tsx.template
packages/ionic-react/src/schematics/application/lib/external-schematic.ts
packages/ionic-react/src/schematics/application/schema.d.ts
packages/ionic-react/src/schematics/application/schema.json

chore(ionic-react): remove --classComponent application option

---

packages/docs/docs/nxtend/introduction.md

docs(nxtend): add @nxtend/ionic-angular to docs introduction

---

e2e/ionic-react-e2e/tests/ionic-react.test.ts
packages/docs/blog/draft/2020-12-02-ionic-react-5.0.0.md
packages/docs/docs/ionic-react/getting-started.md
packages/docs/docs/ionic-react/schematics/application.md
packages/ionic-react/CHANGELOG.md
packages/ionic-react/src/schematics/application/schema.d.ts
packages/ionic-react/src/schematics/application/schema.json
packages/ionic-react/src/schematics/application/schematic.spec.ts
packages/ionic-react/src/schematics/application/schematic.ts

chore(ionic-react): remove --skipFormat application option

---

e2e/ionic-react-e2e/tests/ionic-react.test.ts
packages/docs/blog/draft/2020-12-02-ionic-react-5.0.0.md
packages/docs/docs/ionic-react/getting-started.md
packages/docs/docs/ionic-react/schematics/application.md
packages/ionic-react/CHANGELOG.md
packages/ionic-react/src/schematics/application/lib/external-schematic.ts
packages/ionic-react/src/schematics/application/lib/update-workspace.ts
packages/ionic-react/src/schematics/application/schema.d.ts
packages/ionic-react/src/schematics/application/schema.json
packages/ionic-react/src/schematics/application/schematic.spec.ts
packages/ionic-react/src/schematics/application/schematic.ts

chore(ionic-react): remove --linter application option

---

README.md

Resolves # https://github.com/nxtend-team/nxtend/issues/305

chore(core): add @nxtend/ionic-angular to README

---

packages/ionic-react/src/schematics/application/lib/normalize-options.ts
packages/ionic-react/src/schematics/application/schema.d.ts

chore(ionic-react): remove e2eRoot from app normalized schema

---

packages/docs/blog/draft/2020-12-02-ionic-react-5.0.0.md
packages/ionic-react/CHANGELOG.md
packages/ionic-react/src/schematics/application/files/ionic/blank/src/app/components/ExploreContainer.tsx.template
packages/ionic-react/src/schematics/application/lib/files.ts
packages/ionic-react/src/schematics/application/lib/jest.ts
packages/ionic-react/src/schematics/application/lib/normalize-options.ts
packages/ionic-react/src/schematics/application/lib/update-workspace.ts
packages/ionic-react/src/schematics/application/schema.d.ts
packages/ionic-react/src/schematics/application/schematic.ts

feat(ionic-react): support custom Nx layouts

---

packages/ionic-angular/src/schematics/application/lib/normalize-options.ts
packages/ionic-angular/src/schematics/application/schema.d.ts

chore(ionic-angular): remove unused normalized schema option

---

packages/docs/blog/draft/2020-12-02-ionic-react-5.0.0.md
packages/ionic-react/CHANGELOG.md
packages/ionic-react/migrations.json
packages/ionic-react/package.json
packages/ionic-react/src/migrations/update-5-0-0/update-5-0-0.spec.ts
packages/ionic-react/src/migrations/update-5-0-0/update-5-0-0.ts
packages/ionic-react/src/utils/versions.ts

chore(ionic-react): update Ionic to 5.5.1

---

packages/ionic-angular/CHANGELOG.md
packages/ionic-angular/migrations.json
packages/ionic-angular/package.json
packages/ionic-angular/src/migrations/update-1-1-0/update-1-1-0.spec.ts
packages/ionic-angular/src/migrations/update-1-1-0/update-1-1-0.ts
packages/ionic-angular/src/utils/versions.ts
workspace.json

chore(ionic-angular): update Ionic to 5.5.1

---

.github/workflows/nx-affected.yml

chore(core): run GitHub actions in parallel

---

.github/workflows/nx-affected.yml
e2e/ionic-react-e2e/tests/ionic-react.test.ts
packages/docs/blog/draft/2020-12-02-ionic-react-5.0.0.md
packages/ionic-react/CHANGELOG.md
packages/ionic-react/src/schematics/application/lib/files.ts
packages/ionic-react/src/schematics/application/schema.d.ts
packages/ionic-react/src/schematics/application/schema.json
packages/ionic-react/src/schematics/application/schematic.spec.ts

chore(ionic-react): remove --js application option

---

packages/ionic-react/src/schematics/application/lib/external-schematic.ts
packages/ionic-react/src/schematics/application/lib/jest.ts
packages/ionic-react/src/schematics/application/schematic.spec.ts

chore(ionic-react): simplify Jest implementation

---

packages/ionic-react/src/schematics/application/files/ionic/base/src/app/App.spec.tsx.template
packages/ionic-react/src/schematics/application/files/ionic/base/src/app/App.tsx.template
packages/ionic-react/src/schematics/application/files/ionic/blank/src/app/components/ExploreContainer.tsx.template
packages/ionic-react/src/schematics/application/files/ionic/blank/src/app/pages/Home.tsx.template

chore(ionic-react): standardize starter template

---

e2e/ionic-react-e2e/tests/ionic-react.test.ts

chore(ionic-react): remove unit test runner e2e test

---

packages/docs/docs/ionic-angular/getting-started.md
packages/docs/docs/ionic-angular/schematics/application.md
packages/ionic-angular/CHANGELOG.md
packages/ionic-angular/src/schematics/application/lib/external-schematic.ts
packages/ionic-angular/src/schematics/application/lib/files.ts
packages/ionic-angular/src/schematics/application/schema.d.ts
packages/ionic-angular/src/schematics/application/schema.json
packages/ionic-angular/src/schematics/application/schematic.spec.ts

feat(ionic-angular): support `none` as a unit and e2e test for apps

---

e2e/ionic-react-e2e/tests/ionic-react.test.ts
packages/docs/blog/draft/2020-12-02-ionic-react-11.0.0.md
packages/ionic-react/CHANGELOG.md
packages/ionic-react/src/schematics/application/files/ionic/list/src/app/App.tsx.template
packages/ionic-react/src/schematics/application/files/ionic/list/src/app/components/MessageListItem.css.template
packages/ionic-react/src/schematics/application/files/ionic/list/src/app/components/MessageListItem.tsx.template
packages/ionic-react/src/schematics/application/files/ionic/list/src/app/data/messages.ts.template
packages/ionic-react/src/schematics/application/files/ionic/list/src/app/pages/Home.tsx.template
packages/ionic-react/src/schematics/application/files/ionic/list/src/app/pages/ViewMessage.css.template
packages/ionic-react/src/schematics/application/files/ionic/list/src/app/pages/ViewMessage.tsx.template
packages/ionic-react/src/schematics/application/files/ionic/sidemenu/src/app/App.spec.tsx.template
packages/ionic-react/src/schematics/application/files/ionic/sidemenu/src/app/App.tsx.template
packages/ionic-react/src/schematics/application/files/ionic/sidemenu/src/app/components/ExploreContainer.css.template
packages/ionic-react/src/schematics/application/files/ionic/sidemenu/src/app/components/ExploreContainer.tsx.template
packages/ionic-react/src/schematics/application/files/ionic/sidemenu/src/app/components/Menu.css.template
packages/ionic-react/src/schematics/application/files/ionic/sidemenu/src/app/components/Menu.tsx.template
packages/ionic-react/src/schematics/application/files/ionic/sidemenu/src/app/pages/Page.tsx.template
packages/ionic-react/src/schematics/application/files/ionic/tabs/src/app/App.tsx.template
packages/ionic-react/src/schematics/application/files/ionic/tabs/src/app/components/ExploreContainer.css.template
packages/ionic-react/src/schematics/application/files/ionic/tabs/src/app/components/ExploreContainer.tsx.template
packages/ionic-react/src/schematics/application/files/ionic/tabs/src/app/pages/Tab1.tsx.template
packages/ionic-react/src/schematics/application/files/ionic/tabs/src/app/pages/Tab2.tsx.template
packages/ionic-react/src/schematics/application/files/ionic/tabs/src/app/pages/Tab3.tsx.template
packages/ionic-react/src/schematics/application/lib/files.ts
packages/ionic-react/src/schematics/application/lib/jest.ts
packages/ionic-react/src/schematics/application/schema.d.ts
packages/ionic-react/src/schematics/application/schema.json
packages/ionic-react/src/schematics/application/schematic.spec.ts

feat(ionic-react): add additional starter templates

---

packages/docs/docs/ionic-angular/capacitor.md
packages/docs/docs/ionic-angular/getting-started.md
packages/docs/docs/ionic-react/capacitor.md
packages/docs/docs/ionic-react/getting-started.md
packages/docs/sidebars.js

docs(ionic-react/ionic-angular): better organize Capacitor docs

---

packages/docs/docusaurus.config.js
packages/docs/src/css/custom.css

feat(docs): update theme

---

apps/docs/babel.config.js
apps/docs/blog/2020-06-24-hello-world.md
apps/docs/blog/2020-06-26-ionic-react-2.2.0.md
apps/docs/blog/2020-07-05-capacitor-1.0.0.md
apps/docs/blog/2020-07-05-ionic-react-3.0.0.md
apps/docs/blog/2020-07-11-ionic-react-3.0.2.md
apps/docs/blog/2020-07-16-ionic-react-3.0.3.md
apps/docs/blog/2020-07-22-ionic-react-3.0.4.md
apps/docs/blog/2020-08-15-capacitor-1.1.0.md
apps/docs/blog/2020-09-13-ionic-react-3.1.0.md
apps/docs/blog/2020-11-03-capacitor-2.0.2.md
apps/docs/blog/2020-11-04-ionic-react-4.0.0.md
apps/docs/blog/2020-11-13-ionic-angular-1.0.0.md
apps/docs/docs/doc1.md
apps/docs/docs/nxtend/contributing.md
apps/docs/docusaurus.config.js
package.json
workspace.json
yarn.lock

chore(docs): upgrade @nx-plus/docusaurus

---

packages/capacitor/package.json

fix(capacitor): fix package.json homepage URL

---

packages/ionic-react/src/schematics/application/lib/files.ts

fix(ionic-react): remove logo.svg and star.svg

---

packages/ionic-react/plugins/webpack.ts
packages/ionic-react/src/schematics/application/lib/update-workspace.ts
packages/ionic-react/src/schematics/application/schematic.spec.ts

chore(ionic-react): remove custom Webpack config

---

apps/docs/blog/draft/2020-12-02-nxtend-11.0.0.md
packages/ionic-react/CHANGELOG.md
packages/ionic-react/migrations.json
packages/ionic-react/src/migrations/update-11-0-0/update-11-0-0.spec.ts
packages/ionic-react/src/migrations/update-11-0-0/update-11-0-0.ts
packages/ionic-react/src/utils/versions.ts

chore(ionic-react): update Ionic app dependencies to 5.5.2

---

apps/docs/blog/draft/2020-12-02-nxtend-11.0.0.md
packages/ionic-angular/CHANGELOG.md
packages/ionic-angular/migrations.json
packages/ionic-angular/src/migrations/update-11-0-0/update-11-0-0.spec.ts
packages/ionic-angular/src/migrations/update-11-0-0/update-11-0-0.ts
packages/ionic-angular/src/utils/versions.ts

chore(ionic-angular): update Ionic app dependencies to 5.5.2

---

apps/docs/blog/draft/2020-12-02-nxtend-11.0.0.md
packages/capacitor/CHANGELOG.md
packages/capacitor/migrations.json
packages/capacitor/src/migrations/update-11-0-0/update-11-0-0.spec.ts
packages/capacitor/src/migrations/update-11-0-0/update-11-0-0.ts
packages/capacitor/src/utils/versions.ts

chore(capacitor): update Capacitor app dependencies 2.4.5

---

packages/ionic-react/migrations.json
packages/ionic-react/src/migrations/update-11-0-0/update-webpack-config-11-0-0.spec.ts
packages/ionic-react/src/migrations/update-11-0-0/update-webpack-config-11-0-0.ts

chore(ionic-react): add Webpack config migration

---

apps/docs/blog/draft/2020-12-02-nxtend-11.0.0.md
packages/ionic-react/CHANGELOG.md
packages/ionic-react/src/schematics/application/lib/external-schematic.ts
packages/ionic-react/src/schematics/application/schematic.spec.ts

fix(ionic-react): support --directory with Capacitor projects

---

apps/docs/blog/draft/2020-12-02-nxtend-11.0.0.md
packages/ionic-angular/CHANGELOG.md
packages/ionic-angular/src/schematics/application/lib/external-schematic.ts
packages/ionic-angular/src/schematics/application/schematic.spec.ts

fix(ionic-angular): support --directory with Capacitor projects

---

apps/docs/blog/2021-01-04-nxtend-11.0.0.md
packages/capacitor/package.json
packages/ionic-angular/package.json
packages/ionic-angular/src/utils/versions.ts
packages/ionic-react/package.json
packages/ionic-react/src/utils/versions.ts

release(core): Nxtend 11

---

packages/capacitor/CHANGELOG.md
packages/capacitor/src/migrations/update-11-0-0/update-workspace-json-11-0-0.spec.ts
packages/capacitor/src/migrations/update-11-0-0/update-workspace-json-11-0-0.ts

fix(capacitor): fix workspace migration

---

packages/capacitor/package.json

release(capacitor): 11.0.1

---

apps/docs/docs/capacitor/builders/cap.md

docs(capacitor): fix builder docs

---

apps/docs/blog/2021-01-11-firebase-11.0.0.md
packages/firebase/package.json

release(firebase): 11.0.0

---

packages/ionic-react/CHANGELOG.md
packages/ionic-react/src/migrations/update-11-0-0/update-webpack-config-11-0-0.spec.ts
packages/ionic-react/src/migrations/update-11-0-0/update-webpack-config-11-0-0.ts

fix(ionic-react): fix migration for angular.json users

---

packages/ionic-react/package.json

release(ionic-react): 11.0.1

---

packages/capacitor/CHANGELOG.md
packages/capacitor/package.json

release(capacitor): 11.0.2

---

apps/docs/docs/firebase/builders/firebase.md
apps/docs/docs/firebase/getting-started.md
e2e/firebase-e2e/tests/firebase.test.ts
packages/firebase/CHANGELOG.md
packages/firebase/src/builders/firebase/builder.ts

feat(firebase): support quotes in firebase builder

---

apps/docs/docs/firebase/builders/firebase.md
apps/docs/docs/firebase/getting-started.md
e2e/firebase-e2e/tests/firebase.test.ts
packages/firebase/CHANGELOG.md
packages/firebase/src/builders/firebase/builder.ts

fix(firebase): fix builder quote support

---

apps/docs/docs/capacitor/builders/cap.md
apps/docs/docs/capacitor/getting-started.md
e2e/capacitor-e2e/tests/capacitor.test.ts
packages/capacitor/CHANGELOG.md
packages/capacitor/src/builders/cap/builder.ts

feat(capacitor): support quotes in cap builder

---

.github/workflows/nx-affected.yml
packages/ionic-vue/collection.json
packages/ionic-vue/src/schematics/init/lib/add-capacitor-plugin.ts
packages/ionic-vue/src/schematics/init/lib/add-dependencies.ts
packages/ionic-vue/src/schematics/init/lib/add-vue-plugin.ts
packages/ionic-vue/src/schematics/init/schema.json
packages/ionic-vue/src/schematics/init/schematic.spec.ts
packages/ionic-vue/src/schematics/init/schematic.ts
packages/ionic-vue/src/utils/versions.ts

feat(ionic-vue): add init schematic

---

e2e/ionic-vue-e2e/tests/ionic-vue.spec.ts
packages/ionic-vue/src/schematics/application/files/tabs/src/App.vue.template
packages/ionic-vue/src/schematics/application/files/tabs/src/components/ExploreContainer.vue.template
packages/ionic-vue/src/schematics/application/files/tabs/src/router/index.ts.template
packages/ionic-vue/src/schematics/application/files/tabs/src/views/Tab1.vue.template
packages/ionic-vue/src/schematics/application/files/tabs/src/views/Tab2.vue.template
packages/ionic-vue/src/schematics/application/files/tabs/src/views/Tab3.vue.template
packages/ionic-vue/src/schematics/application/files/tabs/src/views/Tabs.vue.template
packages/ionic-vue/src/schematics/application/files/tabs/tests/unit/example.spec.ts.template
packages/ionic-vue/src/schematics/application/lib/eslint.ts
packages/ionic-vue/src/schematics/application/schematic.ts

feat(ionic-vue): add tabs starter template to application schematic

---

packages/ionic-vue/package.json

chore(ionic-vue): add peer deps

---

packages/ionic-vue/README.md

chore(ionic-vue): add README

---

packages/ionic-vue/src/schematics/application/lib/eslint.ts

chore(ionic-vue): clean up ESLint application schematic file

---

e2e/ionic-vue-e2e/tests/ionic-vue.spec.ts
packages/ionic-vue/src/schematics/application/files/base/tsconfig.json.template
packages/ionic-vue/src/schematics/application/files/sidemenu/src/App.vue.template
packages/ionic-vue/src/schematics/application/files/sidemenu/src/router/index.ts.template
packages/ionic-vue/src/schematics/application/files/sidemenu/src/views/Folder.vue.template
packages/ionic-vue/src/schematics/application/files/sidemenu/tests/unit/example.spec.ts.template
packages/ionic-vue/src/schematics/application/files/tabs/tests/unit/example.spec.ts.template
packages/ionic-vue/src/schematics/application/schema.d.ts

init sidemenu

---

apps/docs/docs/capacitor/getting-started.md
apps/docs/docs/capacitor/schematics/capacitor-project.md

docs(capacitor): npmClient option in capacitor-project schematic

---

packages/ionic-react/CHANGELOG.md
packages/ionic-react/package.json

fix(ionic-react): Nx 11.3.0 support

---

packages/ionic-react/package.json

release(ionic-react): 11.0.2

---

packages/ionic-angular/CHANGELOG.md
packages/ionic-angular/package.json

fix(ionic-angular): Nx 11.3.0 support

---

packages/capacitor/CHANGELOG.md
packages/capacitor/package.json

fix(capacitor): Nx 11.3.0 support

---

packages/firebase/CHANGELOG.md
packages/firebase/package.json

fix(firebase): Nx 11.3.0 support

---

packages/ionic-react/CHANGELOG.md
packages/ionic-react/src/schematics/init/lib/add-capacitor-plugin.ts
packages/ionic-react/src/schematics/init/lib/add-react-plugin.ts
packages/ionic-react/src/schematics/init/schematic.spec.ts

fix(ionic-react): support Node 15 and npm 7

---

README.md

Fixing the link to the Contribution file.

Fix broken Contributing link

---

packages/ionic-angular/CHANGELOG.md
packages/ionic-angular/src/schematics/init/lib/add-angular-plugin.ts
packages/ionic-angular/src/schematics/init/lib/add-capacitor-plugin.ts
packages/ionic-angular/src/schematics/init/schematic.spec.ts

fix(ionic-angular): support Node 15 and npm 7

---

e2e/ionic-angular-e2e/tests/ionic-angular.test.ts
packages/ionic-angular/CHANGELOG.md
packages/ionic-angular/src/schematics/application/files/base/src/app/app.component.spec.ts.template
packages/ionic-angular/src/schematics/application/files/base/src/app/app.component.ts.template
packages/ionic-angular/src/schematics/application/files/base/src/app/app.module.ts.template
packages/ionic-angular/src/schematics/application/files/blank/src/app/app.module.ts.template
packages/ionic-angular/src/schematics/application/files/blank/src/app/home/home.page.spec.ts.template
packages/ionic-angular/src/schematics/application/files/list/src/app/app.module.ts.template
packages/ionic-angular/src/schematics/application/files/list/src/app/home/home.page.spec.ts.template
packages/ionic-angular/src/schematics/application/files/list/src/app/message/message.component.spec.ts.template
packages/ionic-angular/src/schematics/application/files/list/src/app/view-message/view-message.page.spec.ts.template
packages/ionic-angular/src/schematics/application/files/sidemenu/src/app/app.component.html.template
packages/ionic-angular/src/schematics/application/files/sidemenu/src/app/app.component.spec.ts.template
packages/ionic-angular/src/schematics/application/files/sidemenu/src/app/app.component.ts.template
packages/ionic-angular/src/schematics/application/files/sidemenu/src/app/app.module.ts.template
packages/ionic-angular/src/schematics/application/files/sidemenu/src/app/folder/folder.page.spec.ts.template
packages/ionic-angular/src/schematics/application/files/tabs/src/app/app.module.ts.template
packages/ionic-angular/src/schematics/application/files/tabs/src/app/explore-container/explore-container.component.spec.ts.template
packages/ionic-angular/src/schematics/application/files/tabs/src/app/tab1/tab1.page.spec.ts.template
packages/ionic-angular/src/schematics/application/files/tabs/src/app/tab2/tab2.page.spec.ts.template
packages/ionic-angular/src/schematics/application/files/tabs/src/app/tab3/tab3.page.spec.ts.template
packages/ionic-angular/src/schematics/application/files/tabs/src/app/tabs/tabs-routing.module.ts.template
packages/ionic-angular/src/schematics/application/files/tabs/src/app/tabs/tabs.page.spec.ts.template

feat(ionic-angular): update starter templates

---

apps/docs/docs/ionic-angular/schematics/application.md
e2e/ionic-angular-e2e/tests/ionic-angular.test.ts
packages/ionic-angular/CHANGELOG.md
packages/ionic-angular/src/schematics/application/lib/external-schematic.ts
packages/ionic-angular/src/schematics/application/lib/update-eslint-config.ts
packages/ionic-angular/src/schematics/application/schema.d.ts
packages/ionic-angular/src/schematics/application/schema.json
packages/ionic-angular/src/schematics/application/schematic.spec.ts
packages/ionic-angular/src/schematics/application/schematic.ts

feat(ionic-angular): generate applications with ESLint instead of TSLint

---

apps/docs/docs/capacitor/getting-started.md

chore(capacitor): update Capacitor plugin docs

---

packages/capacitor/src/executors/cap/executor.ts
packages/capacitor/src/generators/capacitor-project/generator.spec.ts
packages/capacitor/src/generators/capacitor-project/lib/update-project-package-json.ts

chore(capacitor): use normalizePath instead of join

---

apps/docs/docs/ionic-react/getting-started.md

docs(ionic-react): remove init generator references

---

apps/docs/docs/capacitor/getting-started.md

docs(capacitor): remove init generator references

---

packages/capacitor/package.json

chore(capacitor): move peer deps to deps

---

packages/ionic-angular/CHANGELOG.md
packages/ionic-angular/migrations.json
packages/ionic-angular/src/utils/versions.ts

feat(ionic-angular): update Ionic to 5.8.3

---

packages/ionic-angular/src/generators/application/generator.spec.ts
packages/ionic-angular/src/generators/application/lib/add-dependencies.ts
packages/ionic-angular/src/utils/versions.ts

chore(ionic-angular): remove @ionic-native dependencies

---

packages/capacitor/CHANGELOG.md
packages/capacitor/src/generators/capacitor-project/generator.spec.ts
packages/capacitor/src/generators/capacitor-project/lib/add-project.ts
packages/capacitor/src/migrations/update-12-0-0/capacitor-3-migration-12-0-0.spec.ts
packages/capacitor/src/migrations/update-12-0-0/capacitor-3-migration-12-0-0.ts

feature(capacitor): add run command

---

packages/ionic-angular/CHANGELOG.md
packages/ionic-angular/src/generators/application/lib/update-workspace.ts

fix(ionic-angular): fix asset path when generating an app on Windows

---

packages/capacitor/package.json

release(capacitor): 12.0.0.beta-2

---

packages/capacitor/package.json

fix(capacitor): move @nrwl/workspace to peer deps

---

packages/capacitor/package.json

release(capacitor): 12.0.0

---

.github/workflows/nx-affected.yml
apps/docs/docs/ionic-react/getting-started.md
e2e/ionic-react-e2e/tests/ionic-react.spec.ts
packages/ionic-react/package.json

fix(ionic-react): move @nrwl/workspace to peer deps

---

packages/ionic-react/package.json
packages/ionic-react/src/utils/versions.ts

chore(ionic-react): update @nxtend/capacitor to 12.0.0

---

packages/ionic-react/package.json

release(ionic-react): 12.0.0

---

e2e/ionic-angular-e2e/tests/ionic-angular.spec.ts
packages/ionic-angular/package.json

fix(ionic-angular): move @nrwl/workspace to peer deps

---

packages/ionic-angular/package.json
packages/ionic-angular/src/utils/versions.ts

chore(ionic-angular): update @nxtend/capacitor to 12.0.0

---

packages/ionic-angular/package.json

release(ionic-angular): 12.0.0

---

apps/docs/sidebars.js

docs(ionic-angular): rename schematics to generators

---

packages/firebase/package.json

release(firebase): 12.0.0

---

apps/docs/blog/2021-11-30-nxtend-12.0.0.md

docs(core): 12.0.0

---

packages/capacitor/CHANGELOG.md
packages/capacitor/executors.json
packages/capacitor/generators.json
packages/capacitor/migrations.json
packages/capacitor/package.json
packages/capacitor/src/executors/cap/compat.ts
packages/capacitor/src/generators/capacitor-project/generator.ts
packages/firebase/CHANGELOG.md
packages/firebase/executors.json
packages/firebase/generators.json
packages/firebase/package.json
packages/firebase/src/executors/firebase/compat.ts
packages/firebase/src/generators/firebase-project/generator.ts
packages/ionic-angular/CHANGELOG.md
packages/ionic-angular/executors.json
packages/ionic-angular/generators.json
packages/ionic-angular/package.json
packages/ionic-angular/src/generators/application/generator.ts
packages/ionic-react/CHANGELOG.md
packages/ionic-react/executors.json
packages/ionic-react/generators.json
packages/ionic-react/package.json
packages/ionic-react/src/generators/application/generator.ts

feat(core): Angular CLI support

---

packages/ionic-angular/CHANGELOG.md
packages/ionic-angular/src/generators/application/generator.spec.ts
packages/ionic-angular/src/generators/application/schema.d.ts
packages/ionic-angular/src/generators/application/schema.json

feat(ionic-angular): support --standaloneConfig

---

packages/ionic-react/CHANGELOG.md
packages/ionic-react/src/generators/application/generator.spec.ts
packages/ionic-react/src/generators/application/schema.d.ts
packages/ionic-react/src/generators/application/schema.json

feat(ionic-react): support --standaloneConfig

---

packages/firebase/package.json

release(firebase): 12.1.0

---

packages/capacitor/package.json

release(capacitor): 12.1.0

---

packages/ionic-angular/package.json

release(ionic-angular): 12.1.0

---

packages/ionic-react/package.json

release(ionic-react): 12.1.0

---

.github/workflows/nx-affected.yml
package.json
yarn.lock

chore(docs): upgrade Docusaurus

---

packages/ionic-angular/src/generators/application/lib/add-dependencies.ts

fix(ionic-angular): Wrong dependency in angular package

---

packages/capacitor/CHANGELOG.md
packages/capacitor/package.json

release(capacitor): 13.0.0

---

packages/ionic-react/CHANGELOG.md
packages/ionic-react/package.json

release(ionic-react): 13.0.0

---

packages/ionic-angular/CHANGELOG.md
packages/ionic-angular/package.json

release(ionic-angular): 13.0.0

---

yarn.lock

fix(core): fix Yarn lock file

---

README.md
apps/docs/src/pages/index.js
apps/docs/src/pages/styles.module.css

docs(core): add info about maintenance
