libs/ionic-react/src/schematics/application/schematic.spec.ts, libs/ionic-react/src/schematics/application/schematic.ts, libs/ionic-react/src/utils/versions.ts
This PR adds and configures the Cypress Testing Library.
Resolves #59
=> feat(ionic-react): add and configure Cypress Testing Library dependency

libs/ionic-react/src/schematics/application/schematic.ts
The e2e tests generated by `@nrwl/cypress` do not work with the Ionic blank starter, so this updates the related files to be relevant.
Resolves #53
=> fix(ionic-react): fix generated e2e tests for Ionic

libs/ionic-react/src/utils/versions.ts
Upgrade the version of Ionic in a generated application to 5.0.3.
Resolves #62
=> chore(ionic-react): upgrade Ionic to 5.0.3

libs/ionic-react/migrations.json, libs/ionic-react/src/migrations/update-1-0-1/update-1-0-1.spec.ts, libs/ionic-react/src/migrations/update-1-0-1/update-1-0-1.ts, libs/ionic-react/src/utils/versions.ts
=> chore(ionic-react): upgrade Ionic to 5.0.5

libs/ionic-react/migrations.json, libs/ionic-react/src/migrations/update-1-0-1/update-1-0-1.spec.ts, libs/ionic-react/src/utils/versions.ts
Upgrade ionicons to 5.0.1.
Resolves #75
=> Ionicons 5.0.1

libs/ionic-react/CHANGELOG.md, libs/ionic-react/README.md, libs/ionic-react/collection.json
All schematics from `@nrwl/react` are now available from `@nxtend/ionic-react` unless one is overridden like `application`.
Resolves #99
=> feat(ionic-react): [WIP] extend @nrwl/react schematics

libs/ionic-react/CHANGELOG.md, libs/ionic-react/src/schematics/application/files/jest/src/test-setup.ts.template, libs/ionic-react/src/schematics/application/schematic.spec.ts, libs/ionic-react/src/schematics/application/schematic.ts
=> feat(ionic-react): import @testing-library/jest-dom commands

libs/ionic-react/src/schematics/application/lib/cypress.ts, libs/ionic-react/src/schematics/application/lib/files.ts, libs/ionic-react/src/schematics/application/lib/jest.ts, libs/ionic-react/src/schematics/application/lib/update-workspace.ts, libs/ionic-react/src/schematics/application/schematic.ts
The application schematic was getting rather large, so breaking it down into smaller files was much easier to reason about, and could make it easier to unit test these functions in the future.
Resolves #97
=> cleanup(ionic-react): break application schematic into separate files

libs/ionic-react/CHANGELOG.md, libs/ionic-react/src/schematics/application/lib/files.ts, libs/ionic-react/src/schematics/application/schematic.spec.ts
This plugin generated Jest unit test files even if a user passed `--unitTestRunner none`. This change filters out all test files when adding them to a generated application.
Resolves #96
=> fix(ionic-react): honor `unitTestRunner` flag

.circleci/config.yml
Node 14 was released and is the default version that the CircleCI orb uses, so now I am defaulting to the latest LTS (12).
Resolves #
=> chore(core): use Node 12 for CircleCI

apps/ionic-react-e2e/tests/application.test.ts, libs/ionic-react/CHANGELOG.md, libs/ionic-react/src/schematics/application/files/blank/src/app/__appFileName__.tsx.template, libs/ionic-react/src/schematics/application/schema.d.ts, libs/ionic-react/src/schematics/application/schema.json, libs/ionic-react/src/schematics/application/schematic.spec.ts
In Ionic 5.1.0, the Ionic team added a feature that allows users to eject from the Ionic sanitizer application-wide. This PR adds a flag to the application schematic to implement this new feature.
https://github.com/ionic-team/ionic/pull/20457
Resolves #122
=> feat(ionic-react): support disabling Ionic sanitizer

libs/ionic-react/src/schematics/application/schematic.spec.ts
This change tests that the React and Jest external schematics have been executed in the schematic.
Resolves #133
=> chore(ionic-react): unit test executing external schematics

packages/ionic-react/CHANGELOG.md, packages/ionic-react/package.json, packages/ionic-react/src/schematics/application/schematic.spec.ts, packages/ionic-react/src/schematics/init/lib/add-react-plugin.ts, packages/ionic-react/src/schematics/init/schematic.spec.ts, packages/ionic-react/src/schematics/init/schematic.ts
When the `@nxtend/ionic-react:init` schematic is executed and the user does not have the `@nrwl/react` plugin installed then it will add the `@nrwl/react` dependency with the latest version.
This change ensures that the version of `@nrwl/react` being added matches their `@nrwl/workspace` version to avoid unwanted side effects.
Resolves #182
=> fix(ionic-react): add @nrwl/react version based on the users Nx version

packages/docs/docs/ionic-react/getting-started.md, packages/docs/docs/ionic-react/schematics/init.md, packages/ionic-react/CHANGELOG.md, packages/ionic-react/collection.json, packages/ionic-react/package.json, packages/ionic-react/src/schematics/application/schematic.spec.ts, packages/ionic-react/src/schematics/application/schematic.ts, packages/ionic-react/src/schematics/init/lib/add-capacitor-plugin.ts, packages/ionic-react/src/schematics/init/lib/add-react-plugin.ts, packages/ionic-react/src/schematics/init/schema.d.ts, packages/ionic-react/src/schematics/init/schematic.spec.ts, packages/ionic-react/src/schematics/init/schematic.ts
Due to recent changes, a user would encounter a "collection not found" error if they did not manually add `@nrwl/react` before using the `@nxtend/ionic-react` plugin.
This change now adds a requirement for users to execute the `init` schematic before the `application` schematic, but seems to be the best compromise at the moment.
=> fix(ionic-react): update schematics to better handle adding Nx plugins

e2e/capacitor-e2e/tests/capacitor-project.test.ts
This test is currently failing and was missed at some point due to the way that the dependencies are configured between the ionic-react and capacitor plugin.
Resolves #
=> chore(capacitor): disable e2e test temporarily

package.json, yarn.lock
The @nxtend/ionic-react e2e tests were failing in CI due to a Cypress version mismatch from a sub-dependency of the root `package.json` compared to the one generated in the e2e test. Initializing this plugin will help ensure that these versions stay in sync.
Resolves #
=> fix(ionic-react): initialize @nrwl/cypress to fix e2e tests

e2e/ionic-react-e2e/tsconfig.spec.json
This fixes ESLint references to `@nxtend/ionic-react` from `ionic-react-e2e`.
Resolves #227
=> fix(ionic-react): add "**/*.test.ts" to e2e tsconfig

packages/ionic-react/CHANGELOG.md, packages/ionic-react/migrations.json, packages/ionic-react/src/migrations/update-3-2-0/update-3-2-0.spec.ts, packages/ionic-react/src/utils/versions.ts
Upgrade Ionicons to 5.1.2 in application schematic
Resolves #233
=> chore(ionic-react): upgrade Ionicons app dependency to 5.1.2

e2e/capacitor-e2e/tests/capacitor-project.test.ts
Previously this test was generating an @nxtend/ionic-react application in order to test @nxtend/capacitor. This created an unnecessary implicit dependency between the @nxtend/capacitor e2e tests and @nxtend/ionic-react. This new approach uses @nrwl/react to generate the application which removes that implicit dependency.
Resolves #
=> chore(capacitor): e2e test with @nrwl/react app

e2e/capacitor-e2e/tests/capacitor.test.ts, packages/capacitor/CHANGELOG.md, packages/capacitor/collection.json, packages/capacitor/src/index.ts, packages/capacitor/src/schematics/add-plugin/lib/normalize-options.ts, packages/capacitor/src/schematics/add-plugin/lib/update-project-package-json.ts, packages/capacitor/src/schematics/add-plugin/schema.d.ts, packages/capacitor/src/schematics/add-plugin/schema.json, packages/capacitor/src/schematics/add-plugin/schematic.spec.ts, packages/capacitor/src/schematics/add-plugin/schematic.ts, packages/docs/blog/2020-10-11-capacitor-2.0.0.md, packages/docs/docs/capacitor/schematics/add-plugin.md, packages/docs/sidebars.js
Add an `add-plugin` schematic for adding Capacitor plugins to a project.
Resolves #264
=> feat(capacitor): add add-plugin schematic

packages/ionic-react/plugins/webpack.ts
It does not appear that the Webpack config modifications are necessary with recent versions of Nx. The Nxtend plugin will still be added to the `workspace.json` to make plugin migrations reliable.
Resolves #
=> chore(ionic-react): simplify Webpack implementation

apps/docs/docs/capacitor/builders/cap.md, e2e/capacitor-e2e/tests/capacitor.test.ts, packages/capacitor/src/builders/cap/builder.ts, packages/capacitor/src/builders/cap/schema.d.ts, packages/capacitor/src/builders/cap/schema.json, packages/capacitor/src/migrations/update-11-0-0/update-workspace-json-11-0-0.spec.ts, packages/capacitor/src/migrations/update-11-0-0/update-workspace-json-11-0-0.ts, packages/capacitor/src/schematics/capacitor-project/lib/add-project.ts, packages/capacitor/src/schematics/capacitor-project/schematic.spec.ts
Add a boolean option to the Capacitor `command` builder to determine if the builder should install Node packages before running the desired command. If the option is not specified then the package install will run by default for backwards compatibility.
Resolves #
=> feat(capacitor): add `packageInstall` option to `cap` builder

packages/capacitor/src/migrations/update-11-0-0/update-workspace-json-11-0-0.ts
The 11.0.0 migration for Capacitor did not work for `angular.json` users. This update accounts for both `angular.json` and `workspace.json` users.
Resolves #397
=> fix(capacitor): fix migration for angular.json users

apps/docs/docs/ionic-angular/schematics/application.md, e2e/ionic-angular-e2e/tests/ionic-angular.test.ts, packages/ionic-angular/CHANGELOG.md, packages/ionic-angular/src/schematics/application/files/list/src/app/home/home.page.spec.ts.template, packages/ionic-angular/src/schematics/application/files/list/src/app/message/message.component.spec.ts.template, packages/ionic-angular/src/schematics/application/files/list/src/app/view-message/view-message.page.spec.ts.template, packages/ionic-angular/src/schematics/application/files/sidemenu/src/app/folder/folder.page.spec.ts.template, packages/ionic-angular/src/schematics/application/schema.d.ts, packages/ionic-angular/src/schematics/application/schema.json, packages/ionic-angular/src/schematics/application/schematic.spec.ts
While integrating `@nxtend/ionic-angular` [into nxpm-stack](https://github.com/nxpm/stack/pull/134) I saw it used Karma by default. The rest of the stack uses Jest so I'd love to keep that as the standard.
As these options get passed through to Nx directly, I figured this patch should be enough to create a config similar to the one that's used by `@nrwl/angular` by default.
Let me know if I missed something.
Didn't update any tests as it's a pass-through, the tests do run locally though.
Resolves #333 
For now I'm using `none` to not add Karma config/deps as suggested in the issue above, but the downside of this is that it changes the config for the new libs/components/etc that get generated
=> feat(ionic-angular): enable Jest for Ionic Angular apps

packages/ionic-angular/src/schematics/application/lib/update-eslint-config.ts
I was getting some issues while running the latest version in my unit tests:
```
TypeError: Cannot read property 'find' of undefined
at ../ionic-angular/src/schematics/application/lib/update-eslint-config.ts:14:41
```
and after fixing that:
```
TypeError: Cannot read property 'rules' of undefined
```
If figured it would be good to add some safety guards here.
I'm not sure how to test this in the project - very open for suggestions if you have any!
Resolves #
=> fix: make sure properties can be accessed safely

apps/docs/docs/ionic-angular/generators/page.md, e2e/ionic-angular-e2e/tests/ionic-angular.spec.ts, packages/ionic-angular/CHANGELOG.md, packages/ionic-angular/generators.json, packages/ionic-angular/src/generators/page/files/__name__-routing.module.ts.template, packages/ionic-angular/src/generators/page/files/__name__.module.ts.template, packages/ionic-angular/src/generators/page/files/__name__.page.html.template, packages/ionic-angular/src/generators/page/files/__name__.page.spec.ts.template, packages/ionic-angular/src/generators/page/files/__name__.page.ts.template, packages/ionic-angular/src/generators/page/generator.spec.ts, packages/ionic-angular/src/generators/page/generator.ts, packages/ionic-angular/src/generators/page/lib/update-routing-file.ts, packages/ionic-angular/src/generators/page/schema.d.ts, packages/ionic-angular/src/generators/page/schema.json, yarn.lock
This is just about ready but I wanted to open a draft PR as there are a couple things I'm stuck on at the moment. I've implemented the same basic behaviour as the Ionic CLI for generating pages, but not all options are included at the moment (just the option to specify a directory). I'd like to add all of the options in the future as well (either pre or post merging this basic functionality), and possibly also an option to generate the page in a library instead of in the app itself.
Most of what I've added is reasonably standard, but the code I've added to dynamically add the new route to the app-routing file could require closer inspection. This is the first time I've used an AST to modify a file, it seems to be working as intended but perhaps it could be improved.
The generator is fully …
=> feat(ionic-angular): add page generator
